apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: lightgbm-predictor
spec:
  modelType:
    name: lightgbm
  path: fvt/lightgbm/mushroom
  storage:
    s3:
      secretKey: wml-serving-models
