######################################################### {COPYRIGHT-TOP} ###
# IBM Confidential
# IBM Watson Machine Learning Core
# Copyright IBM Corp. 2021
######################################################### {COPYRIGHT-END} ###
apiVersion: wmlserving.ai.ibm.com/v1
kind: Predictor
metadata:
  name: pytorch-cifar
spec:
  modelType:
    name: pytorch
  path: fvt/pytorch/pytorch-cifar
  storage:
    s3:
      secretKey: wml-serving-models
